---
#

- debug:
    var: ansible_os_family

- include: install-azul-zulu-debian.yml
  when: ansible_os_family == "Debian"


- include: install-azul-zulu-redhat.yml
  when: ansible_os_family == "RedHat"
