---
#
- debug:
    var: java_version

- set_fact: java_update="{{ java_7_update }}" java_build="{{ java_7_build }}"
  when: java_version == 7

- set_fact: java_update="{{ java_8_update }}" java_build="{{ java_8_build }}"
  when: java_version == 8

- debug:
    var: java_update
- debug:
    var: java_build

- name: install curl
  yum: name=curl state=present

- stat: "path=/tmp/jdk-{{ java_version }}.rpm"
  register: rpm_stat

- debug:
    var: rpm_stat

- name: download oracle java rpm
  shell: 'curl -v -j -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/{{ java_version }}u{{ java_update }}-b{{ java_build }}/jdk-{{ java_version }}u{{ java_update }}-linux-x64.rpm -o /tmp/jdk-{{ java_version }}.rpm'
  args:
    creates: /tmp/jdk-{{ java_version }}.rpm
  when: rpm_stat.stat.exists == false

- name: install oracle java jdk
  yum: name=/tmp/jdk-{{ java_version }}.rpm state=present

- name: set java home
  lineinfile:
   dest: "{{ ansible_env.HOME }}/.bash_profile"
   regexp: "^{{ item.start }}"
   line: "{{ item.start }}{{ item.end }}"
   insertbefore: "export PATH"
  with_items:
   - { start: "JAVA_HOME=", end: "/usr/java/jdk1.{{ java_version }}.0_{{ java_update }}" }
   - { start: "PATH=$JAVA_HOME/bin:", end: "$PATH" }
   - { start: "export JAVA_HOME", end: "" }
