---
#
- name: set java home
  lineinfile:
   dest: "{{ ansible_env.HOME }}/.profile"
   regexp: "^{{ item.start }}"
   line: "{{ item.start }}{{ item.end }}"
   insertbefore: "export PATH"
  with_items:
   - { start: "JAVA_HOME=", end: "{{ java_home }}" }
   - { start: "PATH=$JAVA_HOME/bin:", end: "$PATH" }
   - { start: "export JAVA_HOME", end: "" }
